### PR TITLE
Fix to #130 - Exception due to null constant in expression

### PR DESCRIPTION
**Pull request by Kkamikadzee**
Added ignore null constants in update expression.

Fixes: #130

### CODE REVIEW

**Comment by ameckl** [comment]
Hello @artiomchi!

We have a case where the solution for null expression provided in the original thread is not working (current.value ?? existing.value)

```
Timestamp = current.Timestamp > existing.Timestamp && current.Mileage != null    
                    ? current.Timestamp : existing.Timestamp,
```

Do you plan merging this PR?

**Comment by ameckl** [comment]
> Hello @artiomchi!
> 
> 
> 
> We have a case where the solution for null expression provided in the original thread is not working (current.value ?? existing.value)
> 
> 
> 
> ```
> 
> Timestamp = newEntity.Timestamp > existing.Timestamp && newEntity.Mileage != null    
> 
>                     ? newEntity.Timestamp : existing.Timestamp,
> 
> ```
> 
> 
> 
> Do you plan merging this PR?
> 
> 
> 
> edit: Do you have a workaround for this?

Hi @artiomchi can you give us a yes/no for ppl basing their app on your library?

**Comment by artiomchi** [comment]
Hi @Kkamikadzee, unfortunately the PR made a number of other changes, as well as some restructuring for the relational upsert runner, that I wasn't quite sure of. 

The core issue was (as you pointed out) in not filtering null constants from the update expressions, and was just needed a couple lines of code changed to make work.

I've applied just that patch as part of some other work, and applied that in the main branch, and will release it soon.

Thanks for helping out to pinpoint the issue, and sorry for the delayed response

**Comment by dheardal** [comment]
I think this change has had an unintended effect where if the value set in `WhenMatched` is null, then it filters out the parameterised value, and takes the first? parameter value from the list.

Query:
```
 await dbContext
          .TenantUsers
          .Upsert(new UserTenantEntity
          {
              UserId = tenantUser.Id,
              TenantId = tenantUser.TenantId,
              SubjectId = tenantUser.LinkedSubjectId,
              IsEnabled = tenantUser.IsEnabled
          })
          .On(x => new { x.UserId, x.TenantId })
          .WhenMatched(existing => new UserTenantEntity
          {
              IsEnabled = tenantUser.IsEnabled,
              SubjectId = tenantUser.LinkedSubjectId
          })
          .RunAsync();
```

Generated SQL:
```
INSERT INTO "public"."userTenant" AS "T" ("userId", "tenantId", "isEnabled", "subjectId") VALUES (@p0, @p1, @p2, @p3) ON CONFLICT ("userId", "tenantId") DO UPDATE SET "isEnabled" = @p4, "subjectId" = @p0
```

The final argument here should be `@p5` - however it picks `@p0`.

We were lucky that the column type for `subjectId` is not the same as `@p0` so this throws an exception for us, however this could be a silent incorrect update for many users.

**Comment by artiomchi** [comment]
Well dang, you're absolutely right.. I didn't realise it at first, but this PR didn't actually fix the bug. I'm pushing a patch release that should fix the issue. Thanks for bringing it up to me @dheardal

**Pull request closed without merging**
