### PR TITLE
Add methods to get affected rows instead of their count

### PR DESCRIPTION
**Pull request by PhenX**
May be an alternative to https://github.com/artiomchi/FlexLabs.Upsert/issues/29 but could not find an way to make it work on MySQL.

### CODE REVIEW

**Comment by timaiv** [comment]
I think we need `CancellationToken token = default` parameter for `RunAndReturnAsync` method.

**Comment by vaclavholusa** [comment]
> could not find an way to make it work on MySQL.

Will this work? https://stackoverflow.com/a/16592867/2284302


@artiomchi Do you think it's possible to somehow merge this PR even with the MySQL exlusion? This is indeed higly needed feature.

Or maybe release some forked version with output support for mssql?

**Comment by larsmaehlum** [comment]
> > could not find an way to make it work on MySQL.
> 
> Will this work? https://stackoverflow.com/a/16592867/2284302
> 
> @artiomchi Do you think it's possible to somehow merge this PR even with the MySQL exlusion? This is indeed higly needed feature.
> 
> Or maybe release some forked version with output support for mssql?

Would love for this to either be merged in without MySQL support or released as an addon library if feasible.  
Throwing an exception if used on MySQL until a way to implement support would still be better than not having this feature for any database.

**Comment by PhenX** [comment]
Hello, any new on this @artiomchi ?

**Comment by artiomchi** [comment]
Hey @PhenX, thank you for the contribution, and apologies for the very massive delay in looking into this. Unfortunately I couldn't dedicate as much time to this project as I hoped.

Looking into this now, and overall this looks promising. I can't push commits to your branch though, so I might have to make some changes on a branch in my repo, which won't shop up in this PR 👀

**Comment by PhenX** [comment]
> Hey @PhenX, thank you for the contribution, and apologies for the very massive delay in looking into this. Unfortunately I couldn't dedicate as much time to this project as I hoped.
> 
> Looking into this now, and overall this looks promising. I can't push commits to your branch though, so I might have to make some changes on a branch in my repo, which won't shop up in this PR 👀 

Sure! No problem, better massively late than never 😉

**Comment by artiomchi** [comment]
One question - why did you load the items with `.AsNoTracking()`?

Since they're loaded from the database, this should return the latest copy of each record, meaning object tracking could in fact be enabled on them, no? Or are there edge cases that I'm missing, where this could cause an issue?

**Comment by artiomchi** [comment]
No worries.. I'll release it with it enabled, I've added a test, and it seems to behave correctly.
Also had to add a couple patches, including to the inMemory runner, which refused to work :)

**Comment by vaclavholusa** [comment]
> One question - why did you load the items with `.AsNoTracking()`?
> 
> Since they're loaded from the database, this should return the latest copy of each record, meaning object tracking could in fact be enabled on them, no? Or are there edge cases that I'm missing, where this could cause an issue?

`AsNoTracking()` just turns off ChangeTracker for the current result set, it doesn't effect whether that is a fresh copy of the data - that is driven by isolation level.

**Pull request merged**
