### PR TITLE
Update EF to v7 and target .NET 7

### PR DESCRIPTION
**Pull request by mookid8000**
Don't know if this is your planned way forward, but I thought I would offer this as a PR. 🙂 

It solves the MissingMethodException that one gets when running FlexLabs.EntityFrameworkCore.Upsert 6.0.1 on .NET 7.

### CODE REVIEW

**Comment by odinnou** [comment]
You need to upgrade build-*.yml**s**, with .NET 7 version

-  dotnet-version: '**7**.0'
-  and maybe : /p:V6_ONLY=true to /p:V**7**_ONLY=true ( I don't know if it's really needed)

**Comment by artiomchi** [comment]
I'm going to create this as a pre-release first, just to make sure that it works as expected. It'd be great if anyone could test it once it's deployed (I'm just renewing my code signing cert, so that I can deploy it to NuGet)
Will try read up the changelogs in v7, to see if anything else is needed before a final release

**Comment by artiomchi** [comment]
@odinnou
> and maybe : /p:V6_ONLY=true to /p:V**7**_ONLY=true ( I don't know if it's really needed)

You're right - this is no longer needed (was deprecated as part of the v5-v6 upgrade. I'm removing them too

**Comment by chrfin** [comment]
Is the pre-release already available somewhere? Would be happy to test it out as soon as possible 😎...

**Comment by mookid8000** [comment]
@chrfin I made my own release here: https://www.nuget.org/packages/rebusfm.FlexLabs.EntityFrameworkCore.Upsert

You can use that on .NET 7 until the official is out.

**Comment by artiomchi** [comment]
Finally restored my code signing certs and pushed v7.0.0-beta.1 to nuget
If all goes well within a week, I'll promote it to a final build :)

**Comment by odinnou** [comment]
I've test the pre-release, and all good for my usecase ! 
Thanks @artiomchi

**Comment by odinnou** [comment]
> Finally restored my code signing certs and pushed v7.0.0-beta.1 to nuget If all goes well within a week, I'll promote it to a final build :)

Plan to promote it ?
Thanks in advance
kind regards

**Comment by wassim-k** [comment]
Tested v7.0.0-beta.2 prerelease and seems to be working well.

**Comment by artiomchi** [comment]
Thanks for confirming to everyone!
Version 7.0.0 is now released: https://www.nuget.org/packages/FlexLabs.EntityFrameworkCore.Upsert/7.0.0

**Pull request merged**
