### PR TITLE
When matched exclude

### PR DESCRIPTION
**Pull request by gangstatracer**
For my purposes required feature that allows to exclude some columns only from update, but not from insert statement.

### CODE REVIEW

**Comment by artiomchi** [comment]
Looking at the code, you seem to be doing it to update all columns, except for the ones specified.

Isn't it the same as just specifying the columns you want to update?

So instead of 

```csharp
dbContext.Countries.Upsert(newCountry)
    .On(c => c.ISO)
    .WhenMatchedExclude(c => c.Created)
    .Run();
```

You could just use, which will achieve the same thing, and is more explicit
```csharp
dbContext.Countries.Upsert(newCountry)
    .On(c => c.ISO)
    .WhenMatched((c, ic) => new Country
    {
        Name = ic.Name,
        ISO = ic.ISO,
        Updated = ic.Updated,
    })
    .Run();
```

**Comment by gangstatracer** [comment]
I'm writing generic generic storage, that operates with interfaces like 
```
interface IIdentifiable
{
    Guid Id { get; set; }
}
```
so, a haven't full set of properties at point where Upsert call occured, but I have columns which I want to exclude (specified in interface).

**Comment by artiomchi** [comment]
Umm... Thinking about your use-case.. It's NOT going to work anyway.

When you're making an `.Upsert` call, you WILL know which type you're inserting. If you try to call upsert passing an interface collection, the library won't be able to know which type is being inserted, and will fail.

So even if you have a common interface that all your model types are implementing, you'll still have separate `.Upsert` calls in your code for each type, and you should specify the columns that you're updating there.

If I'm wrong, could you show me a full example of how you're using it?

**Comment by gangstatracer** [comment]
Ok, my code looks like this:
```c#
interface IIdentifiable
{
    Guid Id { get; set; }
}

class Country : IIdentifiable
{
    Guid Id { get; set; }
    string ISO { get; set; }
}
class Storage
{
    void Upsert<TEntity>(TEntity entity, Expression<Func<TEntity, object>> onExpression = null)
        where TEntity : IIdentifiable
    {
        using (var context = new MyContext()) // all entity types passed to this methods registered at runtime
        {
            context.Upsert(entity).On(onExpression ?? (e => e.Id)).Run();
        }
    }
}

class SomeBusinessLogicClass
{
    void UpdateCountryByIso(string ISO)
    {
        var storage = new Storage();
        var country1 = new Country 
        { 
            Id = Guid.NewGuid(), // I don't want to find country Id by ISO with extra call to database
            ISO = ISO 
        };
        storage.Upsert(country1, c => c.ISO); // country Id should not be overriden if country already exists
    }
}
```
It works perfectry, but when I call this method with custom "on expression" i don't want Id to be overriden. I hope this exaple sufficient.

**Comment by gangstatracer** [comment]
If you consider this feature excessive, I'll try to dynamically build `WhenMatched` expression, but i'm afraid it would affect perfomace, so first I've tried to offer `WhenMatchedExclude` feature.

**Comment by artiomchi** [comment]
Hi Ivan,

I see.. Yes, this will work. So, why not change your `Storage` class like this then?

```csharp
class Storage
{
    void Upsert<TEntity>(TEntity entity, Expression<Func<TEntity, object>> onExpression = null,
        Expression<Func<TEntity, TEntity, TEntity>> updateExpression)
        where TEntity : IIdentifiable
    {
        using (var context = new MyContext()) // all entity types passed to this methods registered at runtime
        {
            var command = context.Upsert(entity);
            if (onExpression != null)
                command.On(onExpression)
            if (updateExpression != null)
                command.WhenMatched(updateExpression)
            command.Run();
        }
    }
}
```

A couple changes that I made:

* I'm assuming the `Id` column will be the table `[Key]`? If you don't make a `.On()` call, the Upsert command will actually use the `[Key]` columns to make a match by default
* With the same assumption in place, if `WhenMatched` wasn't passed, the upsert command will update all columns that are
  * Not auto generated (see `[DatabaseGenerated]` attribute, or auto increment keys)
  * Not part of the `.On()` column set

  With that in mind, if `Id` is a table key, then the Upsert command will never try to set it's value during in the update statement

**Comment by gangstatracer** [comment]
Artiom, it's greate idea to extend my method. I haven't thought about this because i was implementing my storage on first version of Upsert. Thanks for help and sorry for wasting your time =)

**Comment by artiomchi** [comment]
No problems at all, and you haven't wasted my time - I saw another use case of the library, had a bit of a chat with you, and you gave me a nice idea on how to improve the extensibility of the library!

Thanks for that, and glad you like the library :)

**Pull request closed without merging**
