### PR TITLE
Ensures mysql dummy tests returns a boolean

### PR DESCRIPTION
**Pull request by GaryOma**
Since Mysql version 8.0.24, evaluating a String or a DateTime (for instance) to test if it exists raises a `Truncated incorrect DOUBLE value`.

This is why the test `Upsert_UpdateCondition_ValueCheck_UpdateColumnFromCondition` fails (using MySQL version higher than 8.0.23) for `DbTests_MySql` with the following exception : 

```
FlexLabs.EntityFrameworkCore.Upsert.IntegrationTests.DbTests_MySql.Upsert_UpdateCondition_ValueCheck_UpdateColumnFromCondition
   Source: DbTestsBase.cs line 1682
   Duration: 65 ms

  Message: 
MySqlConnector.MySqlException : Truncated incorrect DOUBLE value: 'hello'

  Stack Trace: 
ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) line 44
MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) line 108
MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) line 456
CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) line 56
MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) line 282
MySqlCommand.ExecuteNonQuery() line 101
RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
RelationalUpsertCommandRunner.Run[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Expression`1 updateCondition, RunnerQueryOptions queryOptions) line 379
UpsertCommandBuilder`1.Run() line 193
DbTestsBase.Upsert_UpdateCondition_ValueCheck_UpdateColumnFromCondition() line 1706
```
This fix aims at ensuring the dummy test evaluates as a boolean and makes all the MySQL tests go green.

### CODE REVIEW

**Comment by jdeksup** [comment]
Please merge this, I need it.

**Comment by artiomchi** [comment]
Looks good to me, thanks for contributing, and sorry it took a while to take a look at it!

**Comment by artiomchi** [comment]
Deployed the build to NuGet under 6.0.2!

**Comment by GaryOma** [comment]
Awesome thanks!

**Pull request merged**
