### PR TITLE
[WIP] Add sqlite 3.24.0 upsert support

### PR DESCRIPTION
**Pull request by LonghronShen**
Since the SQLitePCL.raw package doesn't support Sqlite 3.24.0 now, currently we have to load sqlite 3.24.0 library manually.
Don't merge util SQLitePCL.raw updates or publish as a preview feature since it can be used in a sense.
This workaround tries to force SQLitePCL.raw to load external sqlite3 lib (System wide installed sqlite3 dynamic lib by default), it works on Windows, Linux and OSX.

- [ ] SQLitePCL.raw should update
- [ ] Manaully load library may make Microsoft.EntityFrameworkCore.Sqlite run abnormally, more tests needed

### CODE REVIEW

**Comment by artiomchi** [comment]
Hey @LonghronShen,

I got your message about the failed PR builds. 

Indeed, seems like my build file wouldn't work for pull requests at all!
I've just reconfigured the CI system with a dedicated slimmed down build script for pull requests, then merged that change into your PR, which has done the trick!

One thing to note is that you changed the tests project to run on .net core, and unfortunately that doesn't work well with AppVeyor. As such - it doesn't even find the unit tests. 

If you switch the test project back to .net framework, we'll be able to see if your change passes the tests :)

**Comment by artiomchi** [comment]
While I'm here, could you explain what's the significance of the `SQLitePCLRaw.provider.sqlite3.netstandard11` package, as well as explaining the changes you made in the `Configure` method (a comment in that method would suffice, to make sure that information isn't lost in the future)

**Comment by LonghronShen** [comment]
Hi there,
I have added some comments explaining things that you are concerned.

**Comment by artiomchi** [comment]
Great stuff!

I've taken the liberty to clean up the PR a little bit (cleaned up the comments, csproj file, reverted the package version for the patch). 

At this point it looks pretty good!
I was planning to make a release this week, so I'll actually merge this in and release it as well. The project itself doesn't bundle (or depend) on any version of external packages, so once the latest Sqlite is released - this project will start working straight away (after all, the DbContext init code is going to be in the end project, not this library)

**Comment by LonghronShen** [comment]
I have seen your change!
So far so good, this version is ready to ship now~~

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by artiomchi** [comment]
Brilliant!

Thank you very much for your contribution to this project!

**Pull request merged**
